# Fonts
font_family JetBrainsMono Nerd Font
bold_italic_font auto
font_size 11

# Window
window_padding_width 0 5
# background_opacity 0.95
hide_window_decorations yes
scrollback_indicator_opacity 0.0

# Cursor
cursor_trail 1
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor

# Behavior
enable_audio_bello no
confirm_os_window_close 0
allow_remote_control yes

# Colors
background #0d0d0d
foreground #c1c1c1
cursor #c1c1c1
cursor_text_color #000000
selection_foreground #000000
selection_background #c1c1c1

color0 #000000
color1 #c45555
color2 #9b8d7f
color3 #8c7f70
color4 #7a9aaa
color5 #999999
color6 #a7c7c7
color7 #c1c1c1
color8 #333333
color9 #d47070
color10 #9b8d7f
color11 #8c7f70
color12 #4a5f6a
color13 #999999
color14 #9cb7b7
color15 #c1c1c1
