[main]
font=JetBrainsMono Nerd Font:size=10
width=60
lines=10
prompt="> "
terminal=kitty
match-mode=fuzzy
horizontal-pad=12
vertical-pad=8
inner-pad=6
layer=overlay
exit-on-keyboard-focus-loss=yes

# Stealth Theme
[colors]
background=0d0d0dff
text=999999ff
match=ccccccff
selection=1a1a1aff
selection-text=e0e0e0ff
selection-match=ffffffc0
border=1a1a1aff

# Gruvbox Theme
[colors]
; background=282828ff
; text=ebdbb2ff
; match=fabd2fff
; selection=3c3836ff
; selection-text=fbf1c7ff
; selection-match=fe8019ff
; border=3c3836ff

[border]
width=1
radius=4

[key-bindings]
delete-line-forward=none
prev=Up Control+p Control+k
next=Down Control+n Control+j
cancel=Escape


