#!/bin/bash

scrDir="$HOME/.config/hypr/scripts"

options="Shutdown\nReboot\nSuspend\nLogout"

choice=$(echo -e "$options" | fuzzel --dmenu)

case "$choice" in
"Shutdown")
	systemctl poweroff
	;;
"Reboot")
	systemctl reboot
	;;
"Suspend")
	systemctl suspend
	;;
"Logout")
	loginctl terminate-user $USER
	;;
esac
