#!/bin/bash

# Toggle wlsunset (nightlight)
if pgrep -x "wlsunset" > /dev/null; then
    pkill wlsunset
    notify-send "Nightlight" "Off" -a "wlsunset"
else
    wlsunset -t 4000 -T 4001 &
    notify-send "Nightlight" "On" -a "wlsunset"
fi